config/routes.rb
Rails.application.routes.draw do
  #user routing
  get 'orders/index'
  get 'order_items/index'
  get 'products/index'
  get 'products/show'
  get "/carts" => "carts#index", as:"carts"
  get "/orders/final" => "order_items#final", as:"order_final"
  get 'orders/done' => "orders#done", as:"order_done"
  get 'users/revive' => 'users#revive_page', as:'revive_page'
  post 'revive' => "users#revive", as:"revive"
  patch "/carts/:id/change" => "carts#change", as:"cart_change"
  root 'users#top'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :products, only:[:show, :index] do
    resources :carts, only:[:create, :destroy, :update]
    collection{ get "search" }
  end
  resources :order_items, only:[:index, :create]
  resources :destinations, only:[:create, :update]
  resources :reviews
  resources :orders, only:[:create, :index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #admin routing
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  namespace :admin do
    resources :users
    resources :products
    resources :artists, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :genres, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :labels, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :arrivals, only:[:new, :create, :index]
    resources :orders, only:[:index, :update, :show]
    get 'reviews/new'
    get 'reviews/edit'
    get 'reviews/_index'
    get 'receive' => 'orders#receive', as:'orders_receive'
    get 'done' => 'orders#done', as:'orders_done'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def admin_signed_in?
    current_user.role == 'admin'
  end
end

app/models/arrival.rb
class Arrival < ApplicationRecord
	belongs_to :product
	validates :arrival_count, presence:true, numericality: {greater_than: 0}
	validates :arrival_date, presence:true
end

app/models/artist.rb
class Artist < ApplicationRecord
	include Discard::Model
  	default_scope -> { kept }
	has_many :products
	validates :name, presence:true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :product
  belongs_to :user

  # @total = 0
  # def cart_total(cart)
  #   @total += cart.product.price * cart.count
  # end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user

  validates :address_name, presence:true
  validates :postal_code, presence:true
  validates :address, presence:true
  validates :phone_number, presence:true
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
    has_many :songs, dependent: :destroy
    accepts_nested_attributes_for :songs, allow_destroy: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	include Discard::Model
  	default_scope -> { kept }
	has_many :products
	validates :name, presence:true
end

app/models/label.rb
class Label < ApplicationRecord
	include Discard::Model
  	default_scope -> { kept }
	has_many :products
	validates :name, presence:true
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items, dependent: :destroy
	belongs_to :user
	validate :add_error_sample

	def add_error_sample
    if option.blank?
      errors[:base] << "支払い方法が空欄です"
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }
  has_many :arrivals, dependent: :destroy
  has_many :discs, dependent: :destroy
  accepts_nested_attributes_for :discs, allow_destroy: true
  has_many :songs, through: :discs
  has_many :carts, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy

  attachment :jacket_image

  belongs_to :artist
  belongs_to :label
  belongs_to :genre

  validates :product_name, presence:true
  validates :cd_type, presence:true
  validates :price, presence:true, numericality: {greater_than: 0}
  # validates :stock, presence:true
  validates :sell_status, presence:true

  def stock
    arrivals_count = 0
    buy = 0

    self.arrivals.each do |a|
      arrivals_count += a.arrival_count
    end

    self.order_items.each do |i|
      buy += i.count
    end

    return arrivals_count - buy
  end

  def self.search(search)
    if search
       where(['product_name LIKE ?', "%#{search}%"])
    else
       all
    end
 end

end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
    belongs_to :user
    validates :review, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/user.rb
class User < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts, dependent: :destroy
  has_many :destinations, dependent: :destroy
  has_many :review, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name_characters, presence: true
  validates :first_name_characters, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true

  attachment :profile_image

  def full_name(user)
    user.last_name_characters + user.first_name_characters
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
before_action :check_admin

    def index
        @user = User.with_discarded.find(params[:id])
        @orders = @user.orders
    end

    def show
        @order = Order.find(params[:id])
        @user = User.with_discarded.find(@order.user_id)
    end

    def update
      order = Order.find(params[:id])
      user = User.with_discarded.find(order.user_id)
      user.undiscard
      order.delivery_status = params[:delivery_status]
      order.save
      user.discard
      if order.delivery_status == 0 || order.delivery_status == 1
        redirect_to admin_orders_receive_path
      elsif order.delivery_status == 2
        redirect_to admin_orders_done_path
      end

    end

    def receive
      @orders = Order.where(delivery_status: 0).or(Order.where(delivery_status: 1))
    end

    def done
      @orders = Order.where(delivery_status: 2)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :check_user

  def create
    @order = current_user.orders.new(order_params)
    @order.total_count = params[:total_count]
    @order.total_price = params[:total_price]
    @order.address_name = params[:destination_address_name]
    @order.postal_code = params[:destination_postal_code]
    @order.address = params[:destination_address]
    @order.phone_number = params[:destination_phone_number]
    @order.delivery_status = 0
    if @order.save
      carts = current_user.carts
      carts.each do |cart|
        order_item = OrderItem.find_by(product_id: cart.product_id, order_id: 0)
        order_item.order_id = @order.id
        order_item.save
        cart.destroy
      end
      destinations = current_user.destinations
      destinations.each do |destination|
        destination.destroy
      end
      redirect_to order_done_path
    else
      @destination = Destination.find_by(user_id: current_user.id)
      render "order_items/final"
    end
  end

  def show
      @order = Order.find(params[:id])
  end

  def done
  end

  def index
    @orders = current_user.orders
  end

  private
  def order_params
    params.fetch(:order, {}).permit(:option)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/orders/done.html.erb
<h1> 配送完了一覧 </h1>

<%= link_to "受注一覧", admin_orders_receive_path, :class => "btn btn-primary" %>

<table class="table table-striped">
  <thead>
    <th>購入者</th>
    <th>購入日</th>
    <th>宛名</th>
    <th>購入枚数</th>
    <th>合計金額</th>
    <th>発送状況</th>
    <th></th>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <% user = User.with_discarded.find(order.user_id) %>
      <tr>
        <th><%= user.full_name(user) %></th>
        <th><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></th>
        <th><%= order.address_name %></th>
        <th><%= order.total_count %>枚</th>
        <th><%= order.total_price %>円</th>
        <th><% if order.delivery_status == 0 %>
                発送状況: 配送前
            <% elsif order.delivery_status == 1 %>
              発送状況: 配送中
            <% else order.delivery_status == 2 %>
                発送状況: 配送済み
            <% end %>
        </th>

        <th><%= link_to "詳細", admin_order_path(order) %></th>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/orders/index.html.erb
<h1> 購入履歴 </h1>

<table class="table table-striped">
  <thead>
    <th>購入者</th>
    <th>購入日</th>
    <th>宛名</th>
    <th>購入枚数</th>
    <th>合計金額</th>
    <th>発送状況</th>
    <th></th>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <% user = User.with_discarded.find(order.user_id) %>
      <tr>
        <th><%= user.full_name(user) %></th>
        <th><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></th>
        <th><%= order.address_name %></th>
        <th><%= order.total_count %>枚</th>
        <th><%= order.total_price %>円</th>
        <th><% if order.delivery_status == 0 %>
                発送状況: 配送前
            <% elsif order.delivery_status == 1 %>
              発送状況: 配送中
            <% else order.delivery_status == 2 %>
                発送状況: 配送済み
            <% end %>
        </th>

        <th><%= link_to "詳細", admin_order_path(order) %></th>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/orders/receive.html.erb
<h1> 受注一覧 </h1>

<%= link_to "配送完了一覧", admin_orders_done_path, :class => "btn btn-primary" %>

<table class="table table-striped">
  <thead>
    <th>購入者</th>
    <th>購入日</th>
    <th>宛名</th>
    <th>購入枚数</th>
    <th>合計金額</th>
    <th>発送状況</th>
    <th></th>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <% user = User.with_discarded.find(order.user_id) %>
      <tr>
        <th><%= user.full_name(user) %></th>
        <th><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></th>
        <th><%= order.address_name %></th>
        <th><%= order.total_count %>枚</th>
        <th><%= order.total_price %>円</th>
        <th><% if order.delivery_status == 0 %>
                発送状況: 配送前
            <% elsif order.delivery_status == 1 %>
              発送状況: 配送中
            <% else order.delivery_status == 2 %>
                発送状況: 配送済み
            <% end %>
        <br>
        <%= link_to "配送前", admin_order_path(id: order.id, delivery_status: 0), method: :patch %>
        <%= link_to "配送中", admin_order_path(id: order.id, delivery_status: 1), method: :patch %>
        <%= link_to "配送済み", admin_order_path(id: order.id, delivery_status: 2), method: :patch %>
        </th>

        <th><%= link_to "詳細", admin_order_path(order) %></th>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/orders/show.html.erb
<% @total_fee = 0 %>
<% @delivery_fee = 500 %>
<% @total_fee = @order.total_price - @delivery_fee %>

<h1> 受注詳細 </h1>

<%= link_to '受注一覧へ戻る', admin_orders_receive_path, class: "btn btn-primary" %>
<%= link_to '配送完了一覧へ戻る', admin_orders_done_path, class: "btn btn-primary" %>

<table class="table table-striped">
	<thead>
		<% user = User.with_discarded.find(@order.user_id) %>
		<th>購入者: <%= link_to user.full_name(user), admin_user_path(user)%><br>宛名: <%= @order.address_name %></th>
		<th>購入日: <%= @order.created_at.strftime('%Y/%m/%d %H:%M') %></th>
		<th>郵便番号: <%= @order.postal_code %></th>
		<th>住所: <%= @order.address %></th>
		<th></th>
	</thead>
	<tbody>
		<tr>
			<th></th>
			<th>商品名</th>
			<th>価格</th>
			<th>枚数</th>
			<th></th>
		</tr>

		<% @order.order_items.each do |order_item| %>
		<tr>
			<% product = Product.with_discarded.find(order_item.product_id) %>
			<th><%= attachment_image_tag product, :jacket_image, :fill, 100, 100, :class => 'img-circle', fallback: "no_image.jpg" %></th>
			<th><%= product.product_name %></th>
			<th><%= order_item.price %>円</th>
			<th><%= order_item.count %>枚</th>
			<th></th>
		</tr>
		<% end %>
	</tbody>
	<tfoot>
		<th>購入枚数: <%= @order.total_count %>枚<br>商品の小計: <%= @total_fee %>円</th>
		<th>送料: <%= @delivery_fee %>円</th>
		<th>合計金額: <%= @order.total_price %>円</th>
		<th><% if @order.option == 0 %>
				支払い方法: 銀行振込
			<% elsif @order.option == 1 %>
				支払い方法: クレジットカード
			<% else %>
				支払い方法: 代引き
			<% end %>
		</th>
		<th><% if @order.delivery_status == 0 %>
			 	発送状況: 配送前
			<% elsif @order.delivery_status == 1 %>
			 	発送状況: 配送中
			<% else @order.delivery_status == 2 %>
			 	発送状況: 配送済み
			<% end %>
		</th>
	</tfoot>
</table>