config/routes.rb
Rails.application.routes.draw do
  #user routing
  get 'orders/index'
  get 'order_items/index'
  get 'products/index'
  get 'products/show'
  get "/carts" => "carts#index", as:"carts"
  get "/orders/final" => "order_items#final", as:"order_final"
  get 'orders/done' => "orders#done", as:"order_done"
  get 'users/revive' => 'users#revive_page', as:'revive_page'
  post 'revive' => "users#revive", as:"revive"
  patch "/carts/:id/change" => "carts#change", as:"cart_change"
  root 'users#top'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :products, only:[:show, :index] do
    resources :carts, only:[:create, :destroy, :update]
    collection{ get "search" }
  end
  resources :order_items, only:[:index, :create]
  resources :destinations, only:[:create, :update]
  resources :reviews
  resources :orders, only:[:create, :index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #admin routing
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  namespace :admin do
    resources :users
    resources :products
    resources :artists, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :genres, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :labels, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :arrivals, only:[:new, :create, :index]
    resources :orders, only:[:index, :update, :show]
    get 'reviews/new'
    get 'reviews/edit'
    get 'reviews/_index'
    get 'receive' => 'orders#receive', as:'orders_receive'
    get 'done' => 'orders#done', as:'orders_done'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }
  has_many :arrivals, dependent: :destroy
  has_many :discs, dependent: :destroy
  accepts_nested_attributes_for :discs, allow_destroy: true
  has_many :songs, through: :discs
  has_many :carts, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy

  attachment :jacket_image

  belongs_to :artist
  belongs_to :label
  belongs_to :genre

  validates :product_name, presence:true
  validates :cd_type, presence:true
  validates :price, presence:true, numericality: {greater_than: 0}
  # validates :stock, presence:true
  validates :sell_status, presence:true

  def stock
    arrivals_count = 0
    buy = 0

    self.arrivals.each do |a|
      arrivals_count += a.arrival_count
    end

    self.order_items.each do |i|
      buy += i.count
    end

    return arrivals_count - buy
  end

  def self.search(search)
    if search
       where(['product_name LIKE ?', "%#{search}%"])
    else
       all
    end
 end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
before_action :check_admin

  def new
  	@product = Product.new
  	@disc = @product.discs.build
  	@song = @disc.songs.build
  end

  def create
  	@product = Product.new(product_params)
	  if @product.save
  		flash[:notice] = "商品が登録されました"
  		redirect_to admin_products_path
  	else
  		render "new"
  	end
  end

  def index
  	@products = Product.with_discarded
    @products.each do |product|
      if product.stock == 0
        product.sell_status = "在庫なし"
        product.save
      end
    end
  end

  def show
  	@product = Product.with_discarded.find(params[:id])
  	@discs = Product.with_discarded.find(params[:id]).discs
    @stock = @product.stock
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def update
  	@product = Product.find(params[:id])
  	if @product.update(product_params)
  		flash[:notice] = "商品情報を更新しました"
  		redirect_to admin_product_path(@product)
  	else
  		render "edit"
  	end
  end

  def destroy
  	product = Product.find(params[:id])
	  product.discard
  	redirect_to admin_products_path
  end

  private
  def product_params
  	params.require(:product).permit(:product_name,:cd_type, :artist_id, :jacket_image, :price, :label_id, :genre_id, :stock, :sell_status, :sold_at,
  	 discs_attributes: [:id, :cd_count, :product_id, :_destroy,
  	 songs_attributes: [:id, :song_order, :name, :disc_id, :_destroy]])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
    @products = Product.page(params[:page]).per(10)
    @products.each do |product|
      if product.stock == 0
        product.sell_status = "在庫なし"
        product.save
      end
    end
  end

  def show
    @product = Product.find(params[:id])
    @discs = Product.find(params[:id]).discs
    @stock = @product.stock
    @review = @product.reviews.page(params[:page])
    if user_signed_in?
      @cart = Cart.find_by(product_id: @product.id, user_id: current_user.id)
      if @cart.blank?
        @cart = Cart.new
      end
    end
  end

  def search
    if params[:search].empty?
      @products = Product.all.order(created_at: :desc)
      @products = Product.page(params[:page]).per(10)
      render :index, locals: { products: @products}
    else
      @products = Product.order("created_at DESC").page(params[:page]).per(10).search(params[:search])
      render :index, locals: { products: @products}
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_disc_fields.html.erb
<div class="nested-fields">
    <span><%= link_to_remove_association "ディスクを消す", f %></span>

    <%= f.fields_for :songs do |f| %>
        <%= render "song_fields", f: f %>
    <% end %>

    <label><%= link_to_add_association "曲を追加", f, :songs %></label>
</div>

app/views/admin/products/_song_fields.html.erb
<div class="nested-fields">
	<label>曲名</label>
    <%= f.text_field :name %>
    <span><%= link_to_remove_association "曲を減らす", f %></span>
</div>

app/views/admin/products/edit.html.erb
<% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= @product.errors.count %> error prohibited this user from being saved: </h2>
                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
               <% end %>
                </ul>
              </div>
          <% end %>

<div id="product">
	<h2>商品登録</h2>
	<%= form_for([:admin, @product]) do |f| %>

		<h4>ジャケット編集</h4>
		<%= f.attachment_field :jacket_image %>

		<h4>アーティスト名</h4>
		<%= f.collection_select(:artist_id, Artist.all, :id, :name, { :prompt => "選択してください" , :multiple => true } ) %>

		<h4>アルバム名(商品名)</h4>
		<%= f.text_field :product_name %>

		<h4>価格(数字のみ入力)</h4>
		<%= f.number_field :price %>

		<h4>レーベル名</h4>
		<%= f.collection_select(:label_id, Label.all, :id, :name, { :prompt => "選択してください" , :multiple => true }) %>

		<h4>ジャンル名</h4>
		<%= f.collection_select(:genre_id, Genre.all, :id, :name, { :prompt => "選択してください" , :multiple => true }) %>

		<h4>シングル/アルバム</h4>
		<%= f.select :cd_type, [["シングル","シングル"],["アルバム","アルバム"]], :prompt => "選択してください" %>


		<div class="discs">
		        <%= f.fields_for :discs do |f| %>
		            <%= render "disc_fields", f: f %>
		        <% end %>
	            <label><%= link_to_add_association "ディスクを追加", f, :discs %></label>
		</div>

		<!-- <h4>配送ステータス</h4> -->
		<%# <%= f.select :sell_status, [["配送準備","配送準備"],["配送中","配送中"]], { :prompt => "選択してください" , :multiple => true } %><br><br> %>

		<%= f.submit "更新" %>

	<% end %>

	<%= link_to "商品一覧へ戻る", admin_products_path %>
</div>

app/views/admin/products/index.html.erb
<div id="product">
	<h1 class="product-class">商品一覧</h1>
		<%= link_to "商品入荷", new_admin_arrival_path, class: "btn btn-primary" %>
		<%= link_to "商品登録", new_admin_product_path, class: "btn btn-primary" %>
		<%= link_to "アーティスト登録", new_admin_artist_path, class: "btn btn-primary" %>
		<%= link_to "ジャンル登録", new_admin_genre_path, class: "btn btn-primary" %>
		<%= link_to "レーベル登録", new_admin_label_path, class: "btn btn-primary" %>

	<div class="wrapper clearfix">
	<% @products.each do |product| %>
		<div class="wrapper-contents clearfix">
			<div class="left-index">
			<%= attachment_image_tag product, :jacket_image, :fill, 100, 100, :class => 'img-circle', fallback: "no_image.jpg" %>
			</div>

			<% if product.discarded_at.nil? %>
				<div class="center-index">
						<div class="">商品ID：<%= product.id %></div>
						<div class="">商品名：<%= product.product_name %></div>
						<div class="">アーティスト：<%= product.artist.name %></div>
						<div class="">価格：<%= product.price %></div>
						<div class="">ステータス：<%= product.sell_status %></div>
						<div class="">在庫数：<%= product.stock %></div>
				</div>

				<div class="right-index">
					<%= link_to "詳細", admin_product_path(product), class: "btn btn-primary" %>
					<%= link_to "商品入荷", new_admin_arrival_path, class: "btn btn-primary" %>
					<%= link_to "編集", edit_admin_product_path(product), class: "btn btn-primary" %>
					<%= link_to "削除", admin_product_path(product), method: :delete,  "data-confirm" => "本当に削除しますか？", class:"btn btn-danger btn-next" %>
				</div>
			<% else %>
			  <% artist = Artist.with_discarded.find(product.artist_id) %>
				<div class="center-index">
						<div class="">商品ID：<%= product.id %></div>
						<div class="">商品名：<%= product.product_name %></div>
						<div class="">アーティスト：<%= artist.name %></div>
						<div class="">価格：<%= product.price %></div>
						<div class="">ステータス：削除済み</div>
				</div>

				<div class="right-index">
					<%= link_to "詳細", admin_product_path(product), class: "btn btn-primary" %>
				</div>
		  <% end %>
		</div>
	<% end %>
	</div>

</div>

app/views/admin/products/new.html.erb
<% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= @product.errors.count %> error prohibited this user from being saved: </h2>
                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
               <% end %>
                </ul>
              </div>
          <% end %>

<div id="product">
	<h2>商品登録</h2>
	<%= form_for([:admin, @product]) do |f| %>

		<h4>ジャケット編集</h4>
		<%= f.attachment_field :jacket_image %>

		<h4>アーティスト名</h4>
		<%= f.collection_select(:artist_id, Artist.all, :id, :name, { :prompt => "選択してください" , :multiple => true } ) %><%= link_to "アーティスト登録", new_admin_artist_path, class: "btn btn-primary" %>

		<h4>アルバム名(商品名)</h4>
		<%= f.text_field :product_name %>

		<h4>価格(数字のみ入力)</h4>
		<%= f.number_field :price, min:0 %>

		<h4>レーベル名</h4>
		<%= f.collection_select(:label_id, Label.all, :id, :name, { :prompt => "選択してください" , :multiple => true }) %><%= link_to "レーベル登録", new_admin_label_path, class: "btn btn-primary" %>

		<h4>ジャンル名</h4>
		<%= f.collection_select(:genre_id, Genre.all, :id, :name, { :prompt => "選択してください" , :multiple => true }) %><%= link_to "ジャンル登録", new_admin_genre_path, class: "btn btn-primary" %>

		<h4>シングル/アルバム</h4>
		<%= f.select :cd_type, [["シングル","シングル"],["アルバム","アルバム"]], :prompt => "選択してください" %>



		        <%= f.fields_for :discs do |f| %>
		            <%= render "disc_fields", f: f %>
		        <% end %>
	            <label><%= link_to_add_association "ディスクを追加", f, :discs %></label>



		<%#= f.select :sell_status, [["在庫あり","在庫あり"],["在庫無し","在庫無し"]], { :prompt => "選択してください" , :multiple => true } %><br><br>

		<%= f.submit "登録", class: "btn btn-primary" %>

	<% end %>

	<%= link_to "商品一覧へ戻る", admin_products_path, class: "btn btn-primary" %>
</div>

app/views/admin/products/show.html.erb
<div id="product-show">

	<div class="col-md-5">
		<h2 class="product-title">商品詳細</h2>
		<div class="jacket-img-circle">
		<%= attachment_image_tag @product, :jacket_image, :fill, 150, 150, fallback: "no_image.jpg" %>
		</div>

		<div class="row">
			<div class="col-md-12 wrapper-review">
				<h2>レビュー</h2>

				<table class="table table-striped">
					<tr>
						<th>ユーザ</th>
						<th>レビュー</th>
						<th></th>
						<th></th>
					</tr>

					<% @product.reviews.each do |review| %>
					<tr>
						<th><%= attachment_image_tag review.user, :profile_image, :size => '40x40', :class => 'img-circle', fallback: "no_image.jpg" %>
							<br><%= review.user.full_name(review.user) %></th>
						<th class="review-text"><%= review.review %></th>
						<th><%= link_to "編集", edit_review_path(review) %></th>
						<th><%= link_to "削除", review_path(review), method: :delete %> </th>
					</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>

	<div class="col-md-6  col-md-offset-1 wrapper-review">
		<div class="product-id">
			商品ID：<%= @product.id %>
		</div><br>

		<div class="product-name">
			シングル/アルバム名：<%= @product.product_name %>
		</div><br>

		<% artist = Artist.with_discarded.find(@product.artist_id) %>
		<div class="product-artitst-name">
			アーティスト名：<%= artist.name %>
		</div><br>

		<div class="product-price">
			価格：<%= @product.price %>円(税込)
		</div><br>

		<div class="product-stock">
			在庫数：<%= @stock %>
		</div><br>

		<div class="product-status">
			ステータス：<%= @product.sell_status %>
		</div><br>

		<% label = Label.with_discarded.find(@product.label_id) %>
		<div class="product-label-name">
			レーベル名：<%= label.name %>
		</div><br>

		<% genre = Genre.with_discarded.find(@product.genre_id) %>
		<div class="product-genre-name">
			ジャンル：<%= genre.name %>
		</div><br>

		<div class="product-song-name wrapper-review">
			<h4 class="">曲一覧</h4>
			<% @discs.each.with_index(1) do |disc, index| %>
					<%= (index) %>枚目
			<table class="table table-striped">
				<tr>
					<th>曲番号</th>
					<th>曲名</th>
				</tr>
				<% disc.songs.each.with_index(1) do |song,index| %>
					<tr>
						<th><%= index %></th>
						<th><%= song.name %></th>
					</tr>
					<% end %>
			</table>
			<% end %>
		</div>
	</div>
	<% if @product.discarded_at.nil? %>
	 <%= link_to "編集", edit_admin_product_path(@product), class: "btn btn-primary" %>
	 <%= link_to "削除", admin_product_path(@product), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-danger" %>
	<% end %>
</div>