config/routes.rb
Rails.application.routes.draw do
  #user routing
  get 'orders/index'
  get 'order_items/index'
  get 'products/index'
  get 'products/show'
  get "/carts" => "carts#index", as:"carts"
  get "/orders/final" => "order_items#final", as:"order_final"
  get 'orders/done' => "orders#done", as:"order_done"
  get 'users/revive' => 'users#revive_page', as:'revive_page'
  post 'revive' => "users#revive", as:"revive"
  patch "/carts/:id/change" => "carts#change", as:"cart_change"
  root 'users#top'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :products, only:[:show, :index] do
    resources :carts, only:[:create, :destroy, :update]
    collection{ get "search" }
  end
  resources :order_items, only:[:index, :create]
  resources :destinations, only:[:create, :update]
  resources :reviews
  resources :orders, only:[:create, :index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #admin routing
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  namespace :admin do
    resources :users
    resources :products
    resources :artists, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :genres, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :labels, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :arrivals, only:[:new, :create, :index]
    resources :orders, only:[:index, :update, :show]
    get 'reviews/new'
    get 'reviews/edit'
    get 'reviews/_index'
    get 'receive' => 'orders#receive', as:'orders_receive'
    get 'done' => 'orders#done', as:'orders_done'
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts, dependent: :destroy
  has_many :destinations, dependent: :destroy
  has_many :review, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name_characters, presence: true
  validates :first_name_characters, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true

  attachment :profile_image

  def full_name(user)
    user.last_name_characters + user.first_name_characters
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :check_admin

    def index
        @users = User.with_discarded
    end

    def show
        @user = User.with_discarded.find_by(id: params[:id])
    end

    def edit
        @user = User.with_discarded.find_by(id: params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(params_user)
           flash[:notice] = "ユーザー情報が更新されました"
           redirect_to admin_user_path(@user)
        else
          render "edit"
        end
    end

    def destroy
      user = User.find(params[:id])
      user.discard
      flash[:notice] = "退会しました"
      redirect_to admin_users_path
    end

    private
    def params_user
      params.require(:user).permit(:last_name_characters, :first_name_characters, :last_name_kana,
        :first_name_kana, :email, :profile_image, :postal_code, :address, :phone_number, :password)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :check_user, only:[:show, :edit, :update, :destroy]
before_action :check_logged_in, only:[:revive_page, :revive]
  def top
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params_user)
       flash[:notice] = "ユーザー情報が更新されました"
       redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.discard
    flash[:notice] = "退会しました"
    redirect_to new_user_session_path
  end

  def revive_page
    @user = User.new
  end

  def revive
    user = User.with_discarded.find_by(email: params_user[:email])
    if user.nil?
      flash[:notice] = "有効なメールアドレスではありません"
      redirect_to revive_page_path
    elsif user.discarded_at.nil?
      flash[:notice] = "すでに存在しているアカウントです"
      redirect_to new_user_session_path
    else
      if user.valid_password?(params_user[:password])
        user.undiscard
        flash[:notice] = "アカウントが復元されました"
        redirect_to new_user_session_path
      else
        flash[:notice] = "有効ではないパスワードです"
        redirect_to revive_page_path
      end
    end
  end

  private
  def params_user
    params.require(:user).permit(:last_name_characters, :first_name_characters, :last_name_kana,
      :first_name_kana, :email, :profile_image, :postal_code, :address, :phone_number, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %> error prohibited this user from being saved: </h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
     <% end %>
      </ul>
    </div>
<% end %>

<div class="admin_user_edit_headline">
    <h1>プロフィール編集</h1>
</div>

<div class="container">
    <div class="row">

      <%= form_for @user, url:admin_user_path(@user) do |f| %>
        <div class="col-xs-3">

            <div class="profile1">
                <div class="field1">
                    <div class="label1">
                        <%= f.label "プロフィール画像", for:"form_label" %>
                    </div>
                    <div class="profile">
                    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "70x70", class:"pic_shape" %>
                    <%= f.attachment_field :profile_image %>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-9">

            <div class="field">
                    <%= f.label "性(漢字)　：　", for:"form_label" %><%= f.text_field :last_name_characters, autofocus: true, class:"info1" %>

                    <%= f.label "名(漢字)　：　", for:"form_label" %><%= f.text_field :first_name_characters, autofocus: true, class:"info1" %>
            </div>

            <div class="field">
                    <%= f.label "性(カナ)　：　", for:"form_label" %><%= f.text_field :last_name_kana, autofocus: true, class:"info1" %>

                    <%= f.label "名(カナ)　：　", for:"form_label" %><%= f.text_field :first_name_kana, autofocus: true, class:"info1" %>
            </div>

            <div class="field">
                <div class="label2">
                    <%= f.label "郵便番号", for:"form_label" %>
                </div>
                    <%= f.text_field :postal_code, autofocus: true, class:"info2" %>
            </div>

            <div class="field">
                <div class="label2">
                    <%= f.label "住所", for:"form_label" %>
                </div>
                    <%= f.text_field :address, autofocus: true, class:"info2" %>
            </div>

            <div class="field">
                <div class="label2">
                    <%= f.label "電話番号", for:"form_label" %>
                </div>
                    <%= f.text_field :phone_number, autofocus: true, class:"info2" %>
            </div>

            <div class="field">
                <div class="label2">
                    <%= f.label "メールアドレス", for:"form_label" %>
                </div>
                <div>
                    <%= f.email_field :email, autofocus: true, class:"info2" %>
                </div>
            </div>

            <div class="actions label2">
                <%= link_to "ユーザー一覧へ戻る", admin_users_path, class:"btn btn-primary btn-next" %>
                <% if @user.discarded_at.nil? %>
                 <%= f.submit "更新",class:"btn btn-primary btn-next" %>
                <% else %>
                 退会済み
                <% end %>
            </div>

          </div>
        <% end %>
    </div>
</div>

app/views/admin/users/index.html.erb
<div id="admin_user_index">
    <div class="aui_content">
        <h1>会員一覧</h1>

            <table border="1">
                <tr>
                    <th width=100>id</th>
                    <th width=300>ユーザー名</th>
                    <th width=300>メールアドレス</th>
                    <th width=100>詳細</th>
                    <th width=100>編集</th>
                    <th width=100>退会</th>
                </tr>

                <% @users.each do |user|%>
                <tr>
                    <td><%= user.id%></td>
                    <td><%= user.last_name_characters%><%= user.first_name_characters%></td>
                    <td><%= user.email%></td>
                    <td><%= link_to "詳細", admin_user_path(user)%></td>
                    <td><%= link_to "編集", edit_admin_user_path(user)%></td>
                    <% if user.discarded_at.nil? %>
                    <td><%= link_to "退会", admin_user_path(user), method: :delete, "data-confirm" => "本当に退会しますか？"%> </td>
                    <% else %>
                    <td> 退会済み </td>
                    <% end %>
                </tr>
                <%end%>
            </table>

    </div>
</div>

app/views/admin/users/show.html.erb
<h1>会員詳細</h1>

    <div class="container">
        <div class="row">

        <div class="col-xs-3">

            <div class="profile1">
                <div class="field1">
                    <div class="profile_pic1">
                    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class:"pic_shape" %>
                    </div>
                </div>
            </div>

        </div>

        <div class="col-xs-9">

            <label>氏名</label>
            <p>性：<%= @user.last_name_characters %> 名：<%= @user.first_name_characters %></p>
            <label>カナ</label>
            <p>性：<%= @user.last_name_kana %> 名：<%= @user.first_name_kana %></p>
            <label>郵便番号</label>
            <p>〒<%= @user.postal_code%></p>
            <label>住所</label>
            <p><%= @user.address%></p>
            <label>電話番号</label>
            <p><%= @user.phone_number%></p>
            <label>メールアドレス</label>
            <p><%= @user.email%></p>


            <div class="actions label2">
                <%= link_to "購入履歴", admin_orders_path(id: @user.id), class:"btn btn-primary btn-next" %>
                <%= link_to "ユーザー一覧へ戻る", admin_users_path, class:"btn btn-primary btn-next" %>
                <%= link_to "編集", edit_admin_user_path(@user), class:"btn btn-primary btn-next" %>
            </div>

        </div>
    </div>
</div>