config/routes.rb
Rails.application.routes.draw do
  #user routing
  get 'orders/index'
  get 'order_items/index'
  get 'products/index'
  get 'products/show'
  get "/carts" => "carts#index", as:"carts"
  get "/orders/final" => "order_items#final", as:"order_final"
  get 'orders/done' => "orders#done", as:"order_done"
  get 'users/revive' => 'users#revive_page', as:'revive_page'
  post 'revive' => "users#revive", as:"revive"
  patch "/carts/:id/change" => "carts#change", as:"cart_change"
  root 'users#top'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :products, only:[:show, :index] do
    resources :carts, only:[:create, :destroy, :update]
    collection{ get "search" }
  end
  resources :order_items, only:[:index, :create]
  resources :destinations, only:[:create, :update]
  resources :reviews
  resources :orders, only:[:create, :index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #admin routing
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  namespace :admin do
    resources :users
    resources :products
    resources :artists, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :genres, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :labels, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :arrivals, only:[:new, :create, :index]
    resources :orders, only:[:index, :update, :show]
    get 'reviews/new'
    get 'reviews/edit'
    get 'reviews/_index'
    get 'receive' => 'orders#receive', as:'orders_receive'
    get 'done' => 'orders#done', as:'orders_done'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }
  has_many :arrivals, dependent: :destroy
  has_many :discs, dependent: :destroy
  accepts_nested_attributes_for :discs, allow_destroy: true
  has_many :songs, through: :discs
  has_many :carts, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy

  attachment :jacket_image

  belongs_to :artist
  belongs_to :label
  belongs_to :genre

  validates :product_name, presence:true
  validates :cd_type, presence:true
  validates :price, presence:true, numericality: {greater_than: 0}
  # validates :stock, presence:true
  validates :sell_status, presence:true

  def stock
    arrivals_count = 0
    buy = 0

    self.arrivals.each do |a|
      arrivals_count += a.arrival_count
    end

    self.order_items.each do |i|
      buy += i.count
    end

    return arrivals_count - buy
  end

  def self.search(search)
    if search
       where(['product_name LIKE ?', "%#{search}%"])
    else
       all
    end
 end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
before_action :check_admin

  def new
  	@product = Product.new
  	@disc = @product.discs.build
  	@song = @disc.songs.build
  end

  def create
  	@product = Product.new(product_params)
	  if @product.save
  		flash[:notice] = "商品が登録されました"
  		redirect_to admin_products_path
  	else
  		render "new"
  	end
  end

  def index
  	@products = Product.with_discarded
    @products.each do |product|
      if product.stock == 0
        product.sell_status = "在庫なし"
        product.save
      end
    end
  end

  def show
  	@product = Product.with_discarded.find(params[:id])
  	@discs = Product.with_discarded.find(params[:id]).discs
    @stock = @product.stock
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def update
  	@product = Product.find(params[:id])
  	if @product.update(product_params)
  		flash[:notice] = "商品情報を更新しました"
  		redirect_to admin_product_path(@product)
  	else
  		render "edit"
  	end
  end

  def destroy
  	product = Product.find(params[:id])
	  product.discard
  	redirect_to admin_products_path
  end

  private
  def product_params
  	params.require(:product).permit(:product_name,:cd_type, :artist_id, :jacket_image, :price, :label_id, :genre_id, :stock, :sell_status, :sold_at,
  	 discs_attributes: [:id, :cd_count, :product_id, :_destroy,
  	 songs_attributes: [:id, :song_order, :name, :disc_id, :_destroy]])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
    @products = Product.page(params[:page]).per(10)
    @products.each do |product|
      if product.stock == 0
        product.sell_status = "在庫なし"
        product.save
      end
    end
  end

  def show
    @product = Product.find(params[:id])
    @discs = Product.find(params[:id]).discs
    @stock = @product.stock
    @review = @product.reviews.page(params[:page])
    if user_signed_in?
      @cart = Cart.find_by(product_id: @product.id, user_id: current_user.id)
      if @cart.blank?
        @cart = Cart.new
      end
    end
  end

  def search
    if params[:search].empty?
      @products = Product.all.order(created_at: :desc)
      @products = Product.page(params[:page]).per(10)
      render :index, locals: { products: @products}
    else
      @products = Product.order("created_at DESC").page(params[:page]).per(10).search(params[:search])
      render :index, locals: { products: @products}
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div id="product">
	<h1>商品一覧</h1>

	<%= form_tag search_products_path, method: :get do %>
		<%= text_field_tag "search", params[:search] %>
		<%#= select_tag "search_products", options_for_select([["商品名", "0"],["アーティスト", "1"],["曲名", "2"],["ジャンル", "3"],["レーベル", "4"]]), {:prompt => "選択してください"} %>
		<%= submit_tag "検索" %>
	<% end %>

	<div class="wrapper clearfix">
	<% @products.each do |product| %>
		<div class="wrapper-contents clearfix">
			<div class="left-index">
			<%= attachment_image_tag product, :jacket_image, :fill, 100, 100, :class => 'img-circle', fallback: "no_image.jpg" %>
			</div>

			<div class="center-index">
					<div class="">商品名：<%= product.product_name %></div>
					<div class="">アーティスト：<%= product.artist.name %></div>
					<div class="">価格：<%= product.price %></div>
					<div class="">ステータス：<%= product.sell_status %></div>
					<div class="">在庫数：<%= product.stock %></div>
			</div>

			<div class="right-index">
				<%= link_to "詳細", product_path(product), :class => "btn btn-primary" %>
			</div>
		</div>
	<% end %>
	</div>

</div>

app/views/products/show.html.erb
<div id="product-show">

	<div class="col-md-5">
		<h2 class="product-title">商品詳細</h2>
		<div class="jacket-img-circle">
		<%= attachment_image_tag @product, :jacket_image, :fill, 150, 150, fallback: "no_image.jpg" %>
		</div>

		<div class="row">
			<div class="col-md-12 wrapper-review">
				<h2>レビュー</h2>
					<%= link_to "レビューを書く", new_review_path(product_id: @product.id), :class => "btn btn-primary" %>

				<table class="table table-striped">
					<tr>
						<th>ユーザ</th>
						<th>レビュー</th>
						<th></th>
						<th></th>
					</tr>

					<% @review.each do |review| %>
					<tr>
						<th><%= attachment_image_tag review.user, :profile_image, :size => '40x40', :class => 'img-circle', fallback: "no_image.jpg" %>
							<br><%= review.user.full_name(review.user) %></th>
						<th class="review-text"><%= review.review %></th>
						<% if user_signed_in? %>
							<% if review.user_id == current_user.id %>
							<th><%= link_to "編集", edit_review_path(review) %></th>
							<th><%= link_to "削除", review_path(review), method: :delete %> </th>
							<% end %>
						<% end %>
					</tr>
					<% end %>
				</table>
				<%= paginate @review, class: "paginate" %>
			</div>
		</div>
	</div>

	<div class="col-md-6  col-md-offset-1 wrapper-review">
		<div class="product-name">
			シングル/アルバム名：<%= @product.product_name %>
		</div><br>

		<div class="product-artitst-name">
			アーティスト名：<%= @product.artist.name %>
		</div><br>

		<div class="product-price">
			価格：<%= @product.price %>円(税込)
		</div><br>

		<div class="product-stock">
			在庫数：<%= @stock %>
		</div><br>

		<div class="product-status">
			ステータス：<%= @product.sell_status %>
		</div><br>

		<div class="product-label-name">
			レーベル名：<%= @product.label.name %>
		</div><br>

		<div class="product-genre-name">
			ジャンル：<%= @product.genre.name %>
		</div><br>
		<% if user_signed_in? %>
			<% if @product.stock != 0 %>
			 	<% if @cart.id.blank? %>
			  	<%= form_for [@product, @cart] do |f| %>
						<%=  f.number_field :count, min:0, max: @stock %>
						<%=  f.submit "カートに入れる" %>
					<% end %>
				<% else %>
					<%= form_for [@product, @cart], url: cart_change_path(@cart), action: "patch" do |f| %>
						<%=  f.number_field :count, min:0, max: @stock %>
						<%=  f.submit "カートに入れる" %>
					<% end %>
				<% end %>
			<% end %>
		<% else %>
			<%= link_to "カートに入れる", new_user_session_path %>
		<% end %>


		<div class="product-song-name wrapper-review">
			<h4 class="">曲一覧</h4>
			<% @discs.each.with_index(1) do |disc, index| %>
					<%= (index) %>枚目
			<table class="table table-striped">
				<tr>
					<th>曲番号</th>
					<th>曲名</th>
				</tr>
				<% disc.songs.each.with_index(1) do |song,index| %>
					<tr>
						<th><%= index %></th>
						<th><%= song.name %></th>
					</tr>
					<% end %>
			</table>
			<% end %>
		</div>
	</div>
</div>